/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AlertClient: typeof import('./src/components/AlertClient.vue')['default']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardBody: typeof import('bootstrap-vue-next')['BCardBody']
    BCardHeader: typeof import('bootstrap-vue-next')['BCardHeader']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BSpinner: typeof import('bootstrap-vue-next')['BSpinner']
    BTab: typeof import('bootstrap-vue-next')['BTab']
    BTabs: typeof import('bootstrap-vue-next')['BTabs']
    DayLarge: typeof import('./src/components/DayLarge.vue')['default']
    Days: typeof import('./src/components/Days.vue')['default']
    DaySmall: typeof import('./src/components/DaySmall.vue')['default']
    DescriptionWarning: typeof import('./src/components/DescriptionWarning.vue')['default']
    GrayScaleToggle: typeof import('./src/components/GrayScaleToggle.vue')['default']
    Legend: typeof import('./src/components/Legend.vue')['default']
    MapLarge: typeof import('./src/components/MapLarge.vue')['default']
    MapSmall: typeof import('./src/components/MapSmall.vue')['default']
    PopupRow: typeof import('./src/components/PopupRow.vue')['default']
    Region: typeof import('./src/components/Region.vue')['default']
    Regions: typeof import('./src/components/Regions.vue')['default']
    RegionWarning: typeof import('./src/components/RegionWarning.vue')['default']
    Warning: typeof import('./src/components/Warning.vue')['default']
    Warnings: typeof import('./src/components/Warnings.vue')['default']
  }
}
