export const SET_LOADING = 'Set loading'
export const SET_INITIALIZED = 'Set initialized'
export const SET_TIME_OFFSET = 'Set time offset'
export const SET_SELECTED_DAY = 'Set selected day'
export const SET_WARNINGS = 'Set warnings'
export const SET_VISIBLE_WARNINGS = 'Set visible warnings'
export const SET_WARNING_VISIBILITY = 'Set warning visibility'
export const SET_THEME = 'Set theme'
