types = [
    'cold-weather',
    'flood-level-1',
    'flood-level-2',
    'flood-level-3',
    'forest-fire-weather',
    'grass-fire-weather',
    'hot-weather',
    'pedestrian-safety',
    'rain',
    'sea-icing',
    'sea-thunder-storm',
    'sea-water-height-high-water',
    'sea-water-height-shallow-water',
    'sea-wave-height',
    'sea-wind',
    'thunder-storm',
    'traffic-weather',
    'uv-note',
    'wind',
    'several'
]